# Generated by Django 6.0.2 on 2026-02-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoEntrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Code unique de l'activité", max_length=50, unique=True)),
                ('domaine', models.CharField(max_length=100)),
                ('sous_domaine', models.CharField(max_length=100)),
                ('nom', models.CharField(help_text="Nom de l'activité professionnelle", max_length=200)),
                ('description', models.TextField(help_text="Description succincte de l'activité")),
                ('objectifs', models.TextField(help_text="Objectifs, tâches et missions de l'activité")),
                ('competences', models.TextField(help_text="Compétences requises pour exercer l'activité")),
                ('secteurs', models.TextField(help_text="Secteurs concernés par l'activité")),
                ('public_cible', models.TextField(help_text='Publics cibles (entreprises, particuliers, associations, etc.)')),
                ('mode_prestation', models.CharField(choices=[('en_ligne', 'En ligne'), ('chez_client', 'Chez le client'), ('hybride', 'Hybride')], max_length=20)),
                ('teletravail', models.CharField(choices=[('total', 'Totalement'), ('partiel', 'Partiellement'), ('non', 'Non réalisable')], max_length=20)),
                ('ressources', models.TextField(help_text='Ressources, outils et équipements nécessaires')),
                ('accessibilite_handicap', models.CharField(choices=[('facile', 'Exerçable facilement'), ('amenagement', 'Exerçable avec aménagements'), ('difficile', 'Exerçable avec difficulté'), ('tres_difficile', 'Difficulté élevée à exercer')], max_length=20)),
                ('remarques', models.TextField(blank=True, help_text='Remarques légales ou informations supplémentaires', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
