# Generated by Django 6.0.2 on 2026-02-10 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoEntrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_activite', models.CharField(help_text="Code unique de l'activité (6 chiffres)", max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(6, 'Le code doit contenir au moins 6 caractères'), django.core.validators.RegexValidator(code='invalid_code', message='Utilisez uniquement des chiffres', regex='^[0-9]+$')])),
                ('date_introduction', models.DateField(blank=True, help_text="Date d'introduction de l'activité", null=True)),
                ('nom_activite', models.CharField(help_text="Nom de l'activité professionnelle", max_length=200)),
                ('publics_cibles', models.TextField(help_text='Publics cibles (entreprises, particuliers, associations, etc.)')),
                ('activites_similaires', models.TextField(blank=True, help_text='Activités similaires ou complémentaires', null=True)),
                ('capacite_handicap', models.CharField(choices=[('facile', '✅ Exerçable facilement'), ('amenagement', '⚠️ Exerçable avec aménagements'), ('difficile', '⚠️ Exerçable avec difficulté'), ('tres_difficile', '❌ Difficulté élevée')], max_length=20)),
                ('domaine', models.CharField(max_length=100)),
                ('sous_domaine', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(help_text="Description succincte de l'activité")),
                ('objectifs', models.TextField(help_text="Objectifs, tâches et missions de l'activité")),
                ('competences', models.TextField(help_text="Compétences requises pour exercer l'activité")),
                ('secteurs', models.TextField(help_text="Secteurs concernés par l'activité")),
                ('mode_prestation', models.CharField(choices=[('', '--- Sélectionnez ---'), ('presentiel', 'Présentiel'), ('distance', 'À distance'), ('en_ligne', 'En ligne'), ('client', 'Directement chez le client'), ('hybride', 'Hybride (mixte)'), ('projet', 'Par projet'), ('forfait', 'Forfait')], max_length=20)),
                ('ressources', models.TextField(help_text='Ressources, outils et équipements nécessaires')),
                ('remarques', models.TextField(blank=True, help_text='Remarques légales ou informations supplémentaires', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
