# Generated by Django 6.0.2 on 2026-02-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoentrepreneur',
            name='capacite_handicap',
            field=models.CharField(blank=True, choices=[('facile', '✅ Exerçable facilement'), ('amenagement', '⚠️ Exerçable avec aménagements'), ('difficile', '⚠️ Exerçable avec difficulté'), ('tres_difficile', '❌ Difficulté élevée')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='autoentrepreneur',
            name='competences',
            field=models.TextField(blank=True, help_text="Compétences requises pour exercer l'activité", null=True),
        ),
        migrations.AlterField(
            model_name='autoentrepreneur',
            name='description',
            field=models.TextField(blank=True, help_text="Description succincte de l'activité", null=True),
        ),
        migrations.AlterField(
            model_name='autoentrepreneur',
            name='mode_prestation',
            field=models.CharField(blank=True, choices=[('', '--- Sélectionnez ---'), ('presentiel', 'Présentiel'), ('distance', 'À distance'), ('en_ligne', 'En ligne'), ('client', 'Directement chez le client'), ('hybride', 'Hybride (mixte)'), ('projet', 'Par projet'), ('forfait', 'Forfait')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='autoentrepreneur',
            name='nom_activite',
            field=models.CharField(blank=True, help_text="Nom de l'activité professionnelle", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='autoentrepreneur',
            name='objectifs',
            field=models.TextField(blank=True, help_text="Objectifs, tâches et missions de l'activité", null=True),
        ),
        migrations.AlterField(
            model_name='autoentrepreneur',
            name='publics_cibles',
            field=models.TextField(blank=True, help_text='Publics cibles (entreprises, particuliers, associations, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='autoentrepreneur',
            name='ressources',
            field=models.TextField(blank=True, help_text='Ressources, outils et équipements nécessaires', null=True),
        ),
        migrations.AlterField(
            model_name='autoentrepreneur',
            name='secteurs',
            field=models.TextField(blank=True, help_text="Secteurs concernés par l'activité", null=True),
        ),
    ]
