# Generated by Django 6.0.2 on 2026-02-24 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0002_alter_autoentrepreneur_capacite_handicap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoentrepreneur',
            name='code_activite',
            field=models.CharField(help_text="Code unique de l'activité (5 chiffres)", max_length=5, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'Le code doit contenir au moins 5 caractères'), django.core.validators.RegexValidator(code='invalid_code', message='Utilisez uniquement des chiffres', regex='^[0-9]+$')]),
        ),
    ]
