# Generated by Django 6.0.2 on 2026-02-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0003_alter_autoentrepreneur_code_activite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoentrepreneur',
            name='domaine',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='autoentrepreneur',
            name='sous_domaine',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
